import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja"
      className="h-full w-full text-sm"    
    >
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className="h-full w-full flex bg-background"
      >
        <div className="flex-1 flex">
        {children}
        </div>
      </body>
    </html>
  );
}
